package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String categoria;
     private int calificacion;
     private Set hotels = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(Usuario usuario, String categoria, int calificacion) {
        this.usuario = usuario;
        this.categoria = categoria;
        this.calificacion = calificacion;
    }
    public Categoria(Usuario usuario, String categoria, int calificacion, Set hotels) {
       this.usuario = usuario;
       this.categoria = categoria;
       this.calificacion = calificacion;
       this.hotels = hotels;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }
    public Set getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Set hotels) {
        this.hotels = hotels;
    }




}


