package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name="Ciudad")
public class Ciudad  implements java.io.Serializable {

    @Id
    @Column(name="id")
     private Integer id;
    @Column(name="usuario")
     private Usuario usuario;
    @Column(name="nombre")
     private String nombre;
    @Column(name="pais")
     private String pais;
    @Column(name="continente")
     private String continente;
    
     private Set foros = new HashSet(0);
     
     private Set hotels = new HashSet(0);
     @ManyToMany(cascade = {CascadeType.ALL})
     @JoinTable(name="evento_ciudad", joinColumns={@JoinColumn(name="CIUDAD_ID")}, inverseJoinColumns={@JoinColumn(name="EVENTO_ID")})
     private Set eventos = new HashSet(0);
     private Set itinerarios = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(Usuario usuario, String nombre, String pais, String continente) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.pais = pais;
        this.continente = continente;
    }
    public Ciudad(Usuario usuario, String nombre, String pais, String continente, Set foros, Set hotels, Set eventos, Set itinerarios) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.pais = pais;
       this.continente = continente;
       this.foros = foros;
       this.hotels = hotels;
       this.eventos = eventos;
       this.itinerarios = itinerarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getContinente() {
        return this.continente;
    }
    
    public void setContinente(String continente) {
        this.continente = continente;
    }
    public Set getForos() {
        return this.foros;
    }
    
    public void setForos(Set foros) {
        this.foros = foros;
    }
    public Set getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Set hotels) {
        this.hotels = hotels;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getItinerarios() {
        return this.itinerarios;
    }
    
    public void setItinerarios(Set itinerarios) {
        this.itinerarios = itinerarios;
    }




}


