package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

    private Integer id;
    private Usuario usuario;
    private String nombre;
    private String tipo;
    private Date fechaInicio;
    private Date fechaFin;
    private Set informacionEventos = new HashSet(0);
    private Set ciudads = new HashSet(0);
    private Set foros = new HashSet(0);

    public Evento() {
    }

    public Evento(Usuario usuario, String nombre, String tipo, Date fechaInicio, Date fechaFin) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.tipo = tipo;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }

    public Evento(Usuario usuario, String nombre, String tipo, Date fechaInicio, Date fechaFin, Set informacionEventos, Set ciudads, Set foros) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.tipo = tipo;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.informacionEventos = informacionEventos;
        this.ciudads = ciudads;
        this.foros = foros;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public Set getInformacionEventos() {
        return this.informacionEventos;
    }

    public void setInformacionEventos(Set informacionEventos) {
        this.informacionEventos = informacionEventos;
    }

    public Set getCiudads() {
        return this.ciudads;
    }

    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }

    public Set getForos() {
        return this.foros;
    }

    public void setForos(Set foros) {
        this.foros = foros;
    }

}
