package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Foro generated by hbm2java
 */
public class Foro  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String tema;
     private Date fechaPublicacion;
     private Set ciudads = new HashSet(0);
     private Set eventos = new HashSet(0);
     private Set participacionForos = new HashSet(0);

    public Foro() {
    }

	
    public Foro(Usuario usuario, String tema, Date fechaPublicacion) {
        this.usuario = usuario;
        this.tema = tema;
        this.fechaPublicacion = fechaPublicacion;
    }
    public Foro(Usuario usuario, String tema, Date fechaPublicacion, Set ciudads, Set eventos, Set participacionForos) {
       this.usuario = usuario;
       this.tema = tema;
       this.fechaPublicacion = fechaPublicacion;
       this.ciudads = ciudads;
       this.eventos = eventos;
       this.participacionForos = participacionForos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getParticipacionForos() {
        return this.participacionForos;
    }
    
    public void setParticipacionForos(Set participacionForos) {
        this.participacionForos = participacionForos;
    }




}


