package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private Usuario usuario;
     private String nombre;
     private Set ciudads = new HashSet(0);

    public Hotel() {
    }

	
    public Hotel(Categoria categoria, Usuario usuario, String nombre) {
        this.categoria = categoria;
        this.usuario = usuario;
        this.nombre = nombre;
    }
    public Hotel(Categoria categoria, Usuario usuario, String nombre, Set ciudads) {
       this.categoria = categoria;
       this.usuario = usuario;
       this.nombre = nombre;
       this.ciudads = ciudads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


