package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InformacionEvento generated by hbm2java
 */
public class InformacionEvento  implements java.io.Serializable {


     private Integer id;
     private Evento evento;
     private String tipoRecurso;
     private Set recursos = new HashSet(0);

    public InformacionEvento() {
    }

	
    public InformacionEvento(Evento evento, String tipoRecurso) {
        this.evento = evento;
        this.tipoRecurso = tipoRecurso;
    }
    public InformacionEvento(Evento evento, String tipoRecurso, Set recursos) {
       this.evento = evento;
       this.tipoRecurso = tipoRecurso;
       this.recursos = recursos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public String getTipoRecurso() {
        return this.tipoRecurso;
    }
    
    public void setTipoRecurso(String tipoRecurso) {
        this.tipoRecurso = tipoRecurso;
    }
    public Set getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(Set recursos) {
        this.recursos = recursos;
    }




}


