package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Set informacionEventos = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Recurso(int id, String nombre, String descripcion, Set informacionEventos) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.informacionEventos = informacionEventos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getInformacionEventos() {
        return this.informacionEventos;
    }
    
    public void setInformacionEventos(Set informacionEventos) {
        this.informacionEventos = informacionEventos;
    }




}


