package edu.uniminuto.arqsw.proyecto.Hibernate;
// Generated 26/03/2016 11:41:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String cedula;
     private String nombre;
     private String correo;
     private String rol;
     private Set categorias = new HashSet(0);
     private Set eventos = new HashSet(0);
     private Set ciudads = new HashSet(0);
     private Set foros = new HashSet(0);
     private Set hotels = new HashSet(0);
     private Set participacionForos = new HashSet(0);
     private Set itinerarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String cedula, String nombre, String correo, String rol) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.correo = correo;
        this.rol = rol;
    }
    public Usuario(String cedula, String nombre, String correo, String rol, Set categorias, Set eventos, Set ciudads, Set foros, Set hotels, Set participacionForos, Set itinerarios) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.correo = correo;
       this.rol = rol;
       this.categorias = categorias;
       this.eventos = eventos;
       this.ciudads = ciudads;
       this.foros = foros;
       this.hotels = hotels;
       this.participacionForos = participacionForos;
       this.itinerarios = itinerarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set categorias) {
        this.categorias = categorias;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }
    public Set getForos() {
        return this.foros;
    }
    
    public void setForos(Set foros) {
        this.foros = foros;
    }
    public Set getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Set hotels) {
        this.hotels = hotels;
    }
    public Set getParticipacionForos() {
        return this.participacionForos;
    }
    
    public void setParticipacionForos(Set participacionForos) {
        this.participacionForos = participacionForos;
    }
    public Set getItinerarios() {
        return this.itinerarios;
    }
    
    public void setItinerarios(Set itinerarios) {
        this.itinerarios = itinerarios;
    }




}


